### ISSUE TITLE
Docker build failing

### ISSUE THREAD

**Issue by cecchisandrone** [cjimti/iotwifi#2] opened 2018-03-22 15:35 UTC
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
Building docker image  returns:
```
Sending build context to Docker daemon  2.399MB
Step 1/17 : FROM arm32v7/golang:1.9 AS builder
1.9: Pulling from arm32v7/golang
1296b637c2f2: Pull complete
0e2ab5e048ba: Pull complete
e1a6513627db: Pull complete
397cc0ade5ea: Pull complete
45538672a803: Pull complete
369f691657f3: Pull complete
453516bc4670: Pull complete
bbf59a23e201: Pull complete
Digest: sha256:5c91a39a7dcf0f9ba1f38c2cbe48b9964024e5fcb8408d1f010780f72a9fbba2
Status: Downloaded newer image for arm32v7/golang:1.9
 ---> 1ba8d01a7dcf
Step 2/17 : ENV GOPATH /go
 ---> Running in 770753108df1
Removing intermediate container 770753108df1
 ---> 25c2f05a12e8
Step 3/17 : WORKDIR /go/src
Removing intermediate container d974fec09baa
 ---> 2179870dcc15
Step 4/17 : RUN go get github.com/bhoriuchi/go-bunyan/bunyan
 ---> Running in 6b3427fdec17
The command '/bin/sh -c go get github.com/bhoriuchi/go-bunyan/bunyan' returned a non-zero code: 139
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

1. Run `docker build . -t iotwifi`

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Device: Raspberry Pi B+
  - OS: Linux raspberrypi 4.9.59+ #1047 Sun Oct 29 11:47:10 GMT 2017 armv6l GNU/Linux

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
I'm trying to provide custom HostAPD configuration for TLWN725n USB WIFI dongle.

**Comment by cjimti** [comment] 2018-03-22 22:27
@cecchisandrone Thanks for the report. I'll try to reproduce it tonight. Is it possible you are having network trouble. 

Are you able to `curl -I https://github.com/bhoriuchi/go-bunyan` on the pi and get data?

**Comment by cecchisandrone** [comment] 2018-03-22 22:35
Yes, just tried it.

Sent from iPhone 8

Il 22 mar 2018, 23:27 +0100, Craig Johnston <notifications@github.com>, ha scritto:

**Comment by cjimti** [comment] 2018-03-22 23:15
I'll try figure out why the `go get` command is failing. However I will also update the source in a bit and include the dependencies so `go get` will not be needed.

**Comment by cjimti** [comment] 2018-03-22 23:54
Seems to be working on my development pi. I'm suspecting that it might be docker and it's network.
[![docker build](https://asciinema.org/a/JpjCNohu4VRBAy3yyZefaeura.png)](https://asciinema.org/a/JpjCNohu4VRBAy3yyZefaeura)

Can you try `docker run --rm -it arm32v7/golang:1.9 /bin/sh -c "go get github.com/bhoriuchi/go-bunyan/bunyan` (should simply return without error)

Or shell directly into the container `docker run --rm -it arm32v7/golang:1.9 /bin/sh` and try
`go get github.com/bhoriuchi/go-bunyan/bunyan` to confirm that go was able to download the package you could `ls -l /go/src/github.com/bhoriuchi/go-bunyan` and git a directory listing of the package.

I'm going to close this as a bug but will be curious if this is happening to anyone else. Like I said earlier I'll update the source with the dependencies so it won't need `go get` however the fact that it's not working for you make me think it has something to do with the docker install or network on the pi.

I am also curious about your docker version and pi version. Can you send me the output of these commands.

`cat /proc/cpuinfo | grep Revision`
and 
`docker --version`

Thanks!

**Closed** 2018-03-23 00:25 UTC
Labels: enhancement

**Comment by cjimti** [comment] 2018-03-23 00:28
@cecchisandrone the build no longer needs to run `go get`

**Comment by cecchisandrone** [comment] 2018-03-23 07:18
@cjimti, build fails again with the same error:
```
Sending build context to Docker daemon  2.689MB
Step 1/14 : FROM arm32v7/golang:1.9 AS builder
 ---> 1ba8d01a7dcf
Step 2/14 : ENV GOPATH /go
 ---> Using cache
 ---> 25c2f05a12e8
Step 3/14 : WORKDIR /go/src
 ---> Using cache
 ---> 2179870dcc15
Step 4/14 : RUN mkdir -p /go/src/github.com/cjimti/iotwifi
 ---> Running in 88a2d84ba596
The command '/bin/sh -c mkdir -p /go/src/github.com/cjimti/iotwifi' returned a non-zero code: 139
```
If I run `docker run --rm -it arm32v7/golang:1.9 /bin/sh -c "go get github.com/bhoriuchi/go-bunyan/bunyan"` I receive return code 139.
These are the output of commands you requested:
```
pi@porterbot:~ $ cat /proc/cpuinfo | grep Revision
Revision        : 0010
pi@porterbot:~ $ docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 24
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.59+
Operating System: Raspbian GNU/Linux 9 (stretch)
OSType: linux
Architecture: armv6l
CPUs: 1
Total Memory: 244MiB
Name: porterbot
ID: RLWE:WUTC:3OS6:SZJG:QOVF:UV4E:H73C:E2CQ:GHAC:AKM6:E2XN:WVKG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

```

Anyway I'm pretty sure that everything is due to Rpi B+ that is ARMv6.

**Comment by cecchisandrone** [comment] 2018-03-23 08:21
I solved using arm32v6/golang:alpine. No I have HostAPD error due to missing driver:
`"HOSTAPD GOT: Line 13: invalid/unknown driver 'rtl871xdrv'`
I have to check better.

**Comment by cjimti** [comment] 2018-03-23 16:32
My image will only run on a pi 3 (arm v7) and using the nl80211 driver (with the onboard wifi). I plan to make another public image for the Pi 2 and allow the interface and driver to be configured but it will be a week or so as I am swamped with work at the moment. 

In the output you sent it looks like it is having trouble parsing the config. Did you mount the config?
[see IOT Wifi Configuration](http://pifi.imti.co/#iot-wifi-configuration)

It was also unable to setup the uap0 interface, this could be due to not running the container with `--privileged` and `--net host`. [see Docker run](http://pifi.imti.co/#run-the-iot-wifi-docker-container)

Looks like better error messages are needed on my end. However it is not really intended for a Pi 2 but since I am planning to support the 2 in the future (as well as OrangePi) this helpful, thank you.

**Comment by cecchisandrone** [comment] 2018-03-23 16:58
I used the command line you suggest:

docker run --rm --privileged --net host \
      -v $(pwd)/wificfg.json:/cfg/wificfg.json \
      cjimti/iotwifi

After having edited wificfg.json. It seems that config is parsed correctly but HostAPd fails to run due maybe to a wrong configuration for the USB dongle used.

**Comment by cjimti** [comment] 2018-03-23 17:10
@cecchisandrone thanks for the update. Looks like you are running an  original Pi Model B+. I'll see if I can dig one up around here and also look into supporting more drivers.

This looks interesting [Hostapd driver for RTL8188{C|CU|CUS} wifi chips](https://github.com/pritambaral/hostapd-rtl871xdrv). 

I'll put out a release soon with the ability specify the driver in the config, in your case driver=rtl871xdrv

**Comment by cjimti** [comment] 2018-03-23 17:17
If you want to hard code it in the source for testing you can find where the driver should be specified
[here](https://github.com/cjimti/iotwifi/blob/7ed6e9aaab22d9af522dd5331c3b59c93cecbc8f/iotwifi/commands.go#L55) and [here](https://github.com/cjimti/iotwifi/blob/7ed6e9aaab22d9af522dd5331c3b59c93cecbc8f/iotwifi/wpacfg.go#L92) adding `driver=rtl871xdrv` to the hostapd configuration.

**Comment by cecchisandrone** [comment] 2018-03-23 17:25
Great, I'll give a try. I just tried modifying wpacfg.go. Thanks

**Comment by cecchisandrone** [comment] 2018-03-23 17:46
This is the output now:
```
{"hostname":"porterbot","level":30,"msg":"Starting IoT Wifi...","name":"iotwifi","pid":0,"time":"2018-03-                                                                       23T17:38:22.856Z","v":0}
{"hostname":"porterbot","level":30,"msg":"HTTP Listening on 8080","name":"iotwifi","pid":0,"time":"2018-0                                                                       3-23T17:38:22.867Z","v":0}
{"hostname":"porterbot","level":30,"msg":"Loading IoT Wifi...","name":"iotwifi","pid":0,"time":"2018-03-2                                                                       3T17:38:22.869Z","v":0}
{"hostname":"porterbot","level":30,"msg":"Starting Hostapd.","name":"iotwifi","pid":0,"time":"2018-03-23T                                                                       17:38:22.872Z","v":0}
{"hostname":"porterbot","level":30,"msg":"Hostapd CFG: interface=uap0\nssid=iot-wifi-cfg-3\nhw_mode=g\nch                                                                       annel=6\nmacaddr_acl=0\nauth_algs=1\nignore_broadcast_ssid=0\nwpa=2\nwpa_passphrase=iotwifipass\nwpa_key_                                                                       mgmt=WPA-PSK\nwpa_pairwise=TKIP\nrsn_pairwise=CCMP\ndriver=rtl871xdrv","name":"iotwifi","pid":0,"time":"2                                                                       018-03-23T17:38:23.137Z","v":0}
{"hostname":"porterbot","level":30,"msg":"HOSTAPD GOT: random: Trying to read entropy from /dev/random","                                                                       name":"iotwifi","pid":0,"time":"2018-03-23T17:38:23.253Z","v":0}
{"hostname":"porterbot","level":30,"msg":"HOSTAPD GOT: Configuration file: /dev/stdin","name":"iotwifi","                                                                       pid":0,"time":"2018-03-23T17:38:23.261Z","v":0}
{"hostname":"porterbot","level":30,"msg":"HOSTAPD GOT: Line 13: invalid/unknown driver 'rtl871xdrv'","nam                                                                       e":"iotwifi","pid":0,"time":"2018-03-23T17:38:23.274Z","v":0}
{"hostname":"porterbot","level":30,"msg":"HOSTAPD GOT: 1 errors found in configuration file '/dev/stdin'"                                                                       ,"name":"iotwifi","pid":0,"time":"2018-03-23T17:38:23.282Z","v":0}
{"hostname":"porterbot","level":30,"msg":"HOSTAPD GOT: Failed to set up interface with /dev/stdin","name"                                                                       :"iotwifi","pid":0,"time":"2018-03-23T17:38:23.287Z","v":0}
{"hostname":"porterbot","level":30,"msg":"HOSTAPD GOT: hostapd_init: free iface 0xb6fb4010","name":"iotwi                                                                       fi","pid":0,"time":"2018-03-23T17:38:23.294Z","v":0}
{"hostname":"porterbot","level":30,"msg":"HOSTAPD GOT: Failed to initialize interface","name":"iotwifi","                                                                       pid":0,"time":"2018-03-23T17:38:23.297Z","v":0}
```

**Comment by cjimti** [comment] 2018-03-23 18:01
@cecchisandrone yeah invalid/unknown driver 'rtl871xdrv'. need to get 
[rtl871xdrv](https://github.com/pritambaral/hostapd-rtl871xdrv) driver installed.

**Comment by cjimti** [comment] 2018-03-23 18:03
...but a rebuild hostapd will also be needed. So I'll take a look at it this weekend. Would be nice to have a version that runs on older Pis.

**Comment by cecchisandrone** [comment] 2018-03-23 18:08
Cool, thanks for this. Useless to say how many times in IOT projects this task is done, doing that with your approach is really smart and simple.
